<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120620190028 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
		
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_workspace DROP CONSTRAINT fk_71de9cfbe9bfe681");
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_node DROP CONSTRAINT fk_820cadc88d940019");
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_node DROP CONSTRAINT fk_820cadc84930c33c");
		$this->addSql("ALTER TABLE typo3_typo3_domain_model_domain DROP CONSTRAINT fk_f227e8f6694309e4");
		$this->addSql("ALTER TABLE typo3_typo3_domain_model_user DROP CONSTRAINT fk_e3f98b13e931a6f5");
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_workspace DROP CONSTRAINT fk_71de9cfba762b951");
		$this->addSql("DROP TABLE typo3_typo3cr_domain_model_workspace");
		$this->addSql("DROP TABLE typo3_typo3cr_domain_model_contentobjectproxy");
		$this->addSql("DROP TABLE typo3_typo3_domain_model_site");
		$this->addSql("DROP TABLE typo3_typo3_domain_model_userpreferences");
		$this->addSql("DROP TABLE typo3_typo3_domain_model_user");
		$this->addSql("DROP TABLE typo3_typo3_domain_model_domain");
		$this->addSql("DROP TABLE typo3_media_domain_model_image");
		$this->addSql("DROP TABLE typo3_typo3cr_domain_model_node");
		$this->addSql("DROP TABLE hse_labor_domain_model_student_questions_join");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
		
		$this->addSql("CREATE TABLE typo3_typo3cr_domain_model_workspace (flow3_persistence_identifier VARCHAR(40) NOT NULL, baseworkspace VARCHAR(40) DEFAULT NULL, rootnode VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(flow3_persistence_identifier))");
		$this->addSql("CREATE INDEX idx_71de9cfbe9bfe681 ON typo3_typo3cr_domain_model_workspace (baseworkspace)");
		$this->addSql("CREATE INDEX idx_71de9cfba762b951 ON typo3_typo3cr_domain_model_workspace (rootnode)");
		$this->addSql("CREATE UNIQUE INDEX flow3_identity_typo3_typo3cr_domain_model_workspace ON typo3_typo3cr_domain_model_workspace (name)");
		$this->addSql("CREATE TABLE typo3_typo3cr_domain_model_contentobjectproxy (flow3_persistence_identifier VARCHAR(40) NOT NULL, targettype VARCHAR(255) NOT NULL, targetid VARCHAR(255) NOT NULL, PRIMARY KEY(flow3_persistence_identifier))");
		$this->addSql("CREATE TABLE typo3_typo3_domain_model_site (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, nodename VARCHAR(255) NOT NULL, state INT NOT NULL, siteresourcespackagekey VARCHAR(255) NOT NULL, PRIMARY KEY(flow3_persistence_identifier))");
		$this->addSql("CREATE UNIQUE INDEX flow3_identity_typo3_typo3_domain_model_site ON typo3_typo3_domain_model_site (nodename)");
		$this->addSql("CREATE TABLE typo3_typo3_domain_model_userpreferences (flow3_persistence_identifier VARCHAR(40) NOT NULL, preferences TEXT NOT NULL, PRIMARY KEY(flow3_persistence_identifier))");
		$this->addSql("COMMENT ON COLUMN typo3_typo3_domain_model_userpreferences.preferences IS '(DC2Type:array)'");
		$this->addSql("CREATE TABLE typo3_typo3_domain_model_user (flow3_persistence_identifier VARCHAR(40) NOT NULL, preferences VARCHAR(40) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier))");
		$this->addSql("CREATE UNIQUE INDEX uniq_e3f98b13e931a6f5 ON typo3_typo3_domain_model_user (preferences)");
		$this->addSql("CREATE TABLE typo3_typo3_domain_model_domain (flow3_persistence_identifier VARCHAR(40) NOT NULL, site VARCHAR(40) DEFAULT NULL, hostpattern VARCHAR(255) NOT NULL, PRIMARY KEY(flow3_persistence_identifier))");
		$this->addSql("CREATE INDEX idx_f227e8f6694309e4 ON typo3_typo3_domain_model_domain (site)");
		$this->addSql("CREATE TABLE typo3_media_domain_model_image (flow3_persistence_identifier VARCHAR(40) NOT NULL, resource VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, width INT NOT NULL, height INT NOT NULL, type INT NOT NULL, imagevariants TEXT NOT NULL, PRIMARY KEY(flow3_persistence_identifier))");
		$this->addSql("CREATE INDEX idx_7fa2358dbc91f416 ON typo3_media_domain_model_image (resource)");
		$this->addSql("COMMENT ON COLUMN typo3_media_domain_model_image.imagevariants IS '(DC2Type:array)'");
		$this->addSql("CREATE TABLE typo3_typo3cr_domain_model_node (flow3_persistence_identifier VARCHAR(40) NOT NULL, workspace VARCHAR(40) DEFAULT NULL, contentobjectproxy VARCHAR(40) DEFAULT NULL, version INT DEFAULT 1 NOT NULL, path VARCHAR(255) NOT NULL, parentpath VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, sortingindex INT DEFAULT NULL, properties TEXT NOT NULL, contenttype VARCHAR(255) NOT NULL, removed BOOLEAN NOT NULL, hidden BOOLEAN NOT NULL, hiddenbeforedatetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, hiddenafterdatetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, hiddeninindex BOOLEAN NOT NULL, accessroles TEXT NOT NULL, PRIMARY KEY(flow3_persistence_identifier))");
		$this->addSql("CREATE INDEX idx_820cadc88d940019 ON typo3_typo3cr_domain_model_node (workspace)");
		$this->addSql("CREATE INDEX idx_820cadc84930c33c ON typo3_typo3cr_domain_model_node (contentobjectproxy)");
		$this->addSql("COMMENT ON COLUMN typo3_typo3cr_domain_model_node.properties IS '(DC2Type:array)'");
		$this->addSql("COMMENT ON COLUMN typo3_typo3cr_domain_model_node.accessroles IS '(DC2Type:array)'");
		$this->addSql("CREATE TABLE hse_labor_domain_model_student_questions_join (labor_student VARCHAR(40) NOT NULL, labor_question VARCHAR(40) NOT NULL, PRIMARY KEY(labor_student, labor_question))");
		$this->addSql("CREATE INDEX idx_392ae2d978820f30 ON hse_labor_domain_model_student_questions_join (labor_student)");
		$this->addSql("CREATE INDEX idx_392ae2d92f31b954 ON hse_labor_domain_model_student_questions_join (labor_question)");
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_workspace ADD CONSTRAINT fk_71de9cfbe9bfe681 FOREIGN KEY (baseworkspace) REFERENCES typo3_typo3cr_domain_model_workspace (flow3_persistence_identifier) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_workspace ADD CONSTRAINT fk_71de9cfba762b951 FOREIGN KEY (rootnode) REFERENCES typo3_typo3cr_domain_model_node (flow3_persistence_identifier) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE typo3_typo3_domain_model_user ADD CONSTRAINT fk_e3f98b13e931a6f5 FOREIGN KEY (preferences) REFERENCES typo3_typo3_domain_model_userpreferences (flow3_persistence_identifier) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE typo3_typo3_domain_model_user ADD CONSTRAINT fk_e3f98b1321e3d446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES typo3_party_domain_model_abstractparty (flow3_persistence_identifier) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE typo3_typo3_domain_model_domain ADD CONSTRAINT fk_f227e8f6694309e4 FOREIGN KEY (site) REFERENCES typo3_typo3_domain_model_site (flow3_persistence_identifier) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE typo3_media_domain_model_image ADD CONSTRAINT fk_7fa2358dbc91f416 FOREIGN KEY (resource) REFERENCES typo3_flow3_resource_resource (flow3_persistence_identifier) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_node ADD CONSTRAINT fk_820cadc88d940019 FOREIGN KEY (workspace) REFERENCES typo3_typo3cr_domain_model_workspace (flow3_persistence_identifier) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE typo3_typo3cr_domain_model_node ADD CONSTRAINT fk_820cadc84930c33c FOREIGN KEY (contentobjectproxy) REFERENCES typo3_typo3cr_domain_model_contentobjectproxy (flow3_persistence_identifier) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE hse_labor_domain_model_student_questions_join ADD CONSTRAINT fk_392ae2d978820f30 FOREIGN KEY (labor_student) REFERENCES hse_labor_domain_model_student (flow3_persistence_identifier) NOT DEFERRABLE INITIALLY IMMEDIATE");
		$this->addSql("ALTER TABLE hse_labor_domain_model_student_questions_join ADD CONSTRAINT fk_392ae2d92f31b954 FOREIGN KEY (labor_question) REFERENCES hse_labor_domain_model_question (flow3_persistence_identifier) NOT DEFERRABLE INITIALLY IMMEDIATE");
	}
}

?>